version: '2'

services:
        api:
                container_name: todo-app
                restart: always
                build: .
                ports: 
                        - "3000:3000"
                links:
                        - db
                networks:
                        - network

        db:
                container_name: mongodb
                image: mvertes/alpine-mongo
                volumes: 
                        - ./data:/data/db
                ports:
                        - "27017:27017"
                networks:
                        - network
networks:
          network:
                      driver: bridge
